### ISSUE TITLE
Plans for Waterfox Alpha packages?

### ISSUE THREAD

**Issue by notpushkin** [hawkeye116477/waterfox-deb#27]
Hi there! First of all, thanks for the hard work you're doing maintaining this repository :) I was wondering if you have any plans on adding Waterfox Alpha packages ([68.0.1a at the moment](https://www.waterfox.net/releases/)) to the repo?

**Comment by hawkeye116477** [comment]
Problem is that currently not all Ubuntu releases has needed packages to compile waterfox-alpha (cbindgen, node.js 11). Cbindgen is only on Disco and Eoan. The highest Nodejs version is 10.15.2 on Disco, waterfox-alpha supposedly requires node 8.14+, but currently it doesn't compile with nodejs8 and nodejs10, errors appear, only nodejs11 and 12 works correct :smile: On Debian problem is even more complicated, because stable Debian doesn't have required packages.

For now, I'm consider making rpm package for SUSE Leap and AppImage based on it.

**Comment by notpushkin** [comment]
If I understand correctly, Node.js is compile-time only dependence? Perhaps installing it via [Nodesource](https://github.com/nodesource/distributions) on the build server would be an acceptable solution for the time being? (I'm not sure if OBS allows that though)

**Comment by hawkeye116477** [comment]
@notpushkin Yes, it's build-depend. Unfortunately it's not possible to install that on OBS. I'll see what I can do, maybe I'll try to make nodejs12 and cbindgen for Ubuntu Bionic+.

**Comment by hawkeye116477** [comment]
Ok, it seems that works fine with nodejs8, but previously I tried latest commit, now I tried from tag.
But for now LTO will be disabled on Xenial, cuz I got `undefined reference to `gMozillaPoisonValue'` and then linker fails, for other Ubuntu versions it works fine. For now no package for Debian 9, cuz it hasn't required node and nasm version, but it will rather come, I just probably port it, as I did for CentOS. Now I'm doing rebuild and should be available today much later :smile:

**Comment by hawkeye116477** [comment]
@notpushkin Good news for you. Package for Debian 10, Testing, Unstable, Ubuntu Xenial, Bionic, Disco and Eoan (Next) is ready now :smile:

**Comment by hawkeye116477** [comment]
Now I have all depends for Debian 9, so soon will be published with LTO+PGO after announcement of Alpha 2 on official website. For other distros also now will be with LTO & PGO, it seems that with new version I has more successful builds with LTO & PGO :smile:

**Comment by notpushkin** [comment]
Awesome news! Once again, thank you so much for your great work :)
