### ISSUE TITLE
No beta/current builds for ubuntu?

### ISSUE THREAD

**Issue by BobbyWibowo** [hawkeye116477/waterfox-deb#28]
Hi, is there any specific reason as to why beta/current is disabled for Ubuntu? I'm specifically looking for 18.04/bionic builds.

**Comment by hawkeye116477** [comment]
@BobbyWibowo It's disabled, because I wanted now build package for other distros and if I fix something then if I won't disable it, then it triggers rebuild, but fix was for other distros (not Ubuntu), so I disabled it, but it's available.
https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-beta

**Comment by BobbyWibowo** [comment]
Ah yeah, I wasn't being specific, I actually wanted the kde patched version instead cause I'm actually on KDE neon (which to be fair is merely Ubuntu 18.04 LTS with KDE apps steroid)

**Comment by hawkeye116477** [comment]
@BobbyWibowo If you want only KDE dialog, then for WF Current, you can use magic of xdg-desktop-portal-kde (`https://www.reddit.com/r/kde/comments/a5cxwk/firefox_v64_can_now_use_the_kde_file_selection/`), but if you have libgtk-3-0 lower than 3.24.4, then may be some problems.
I will soon publish package with KDE patches for Ubuntu.

**Comment by hawkeye116477** [comment]
@BobbyWibowo You can install waterfox-current-kde for 18.04 now :smile:

**Comment by BobbyWibowo** [comment]
Thanks, can confirm `waterfox-current-kde` installs & runs just fine!
